#!/usr/bin/ruby -w
# password_handler
#
# Notes:
#
#   rand() sucks.  It seeds from the time.  /dev/urandom is used to get some
#   good entropy.

for utility in ["stty", "printf", "dd", "echo", "sha512sum", "xclip", "base64"]
  if ! (system "which #{utility} > /dev/null 2>&1")
  then
    puts "You need to have #{utility} installed.  Exiting."
    exit false
  end
end

STDOUT.sync = true
# Work in the home directory only, for simplicity.
Dir.chdir
list_file_name = ".password_handler_v2_site_list"
test_hash_file_name = ".password_handler_v2_test_hash"
test_salt_file_name = ".password_handler_v2_test_salt"
site = ""


# Get password and don't print it.
print "Master password:  "
`stty -echo`
password = gets.chomp
`stty echo`
print "\n"

# Test for password correctness.
if ! (File.exists? test_hash_file_name and File.exists? test_salt_file_name)
then
  print "Confirm master password:  "
  `stty -echo`
  confirm_password = gets.chomp
  `stty echo`
  print "\n"
  if password == confirm_password
  then
    test_hash_file_handle = File.new test_hash_file_name, "w"
    puts "Created: #{test_hash_file_name}"
    test_salt_file_handle = File.new test_salt_file_name, "w"
    puts "Created: #{test_salt_file_name}"
    test_salt = `dd if=/dev/urandom bs=1 count=1024 2>/dev/null | base64 --wrap=0`
    test_salt_file_handle << test_salt
    test_hash = `echo \"#{test_salt}#{password}\" | sha512sum -`
    test_hash_file_handle << test_hash
    test_salt_file_handle.close
    test_hash_file_handle.close
  else
    puts "Passwords do not match."
    exit
  end
end

test_hash = `echo \"#{test_salt}#{password}\" | sha512sum -`
saved_test_salt = File.read(test_salt_file_name)
saved_test_hash = File.read(test_hash_file_name)

if test_hash != saved_test_hash
then
  puts "Password seems wrong.  Exiting."
  exit
end

while true
  # generate list of known sites
  list = Array.new
  if ! File.exists? list_file_name
  then
    list_file_handle = File.new list_file_name, "w"
    puts "Created: #{list_file_name}"
    list_file_handle.close
  end
  list_file_handle = File.open list_file_name, "r"
  while entry = list_file_handle.gets
    list.push Hash.new
    list.last["salt"] = entry.chomp.sub(/\A[0-9]* (.*)\Z/, "\1")
    list.last["site"] = entry.chomp.sub(/\A([0-9]*) .*\Z/, "\1")
  end
  list_file_handle.close

  # get site name
  while true
    print "Site (name, index number, [l]ist, or [q]uit):  "
    if (site = gets.chomp) =~ /^[Ll]$/
    # paging might be nice, here
    then list.each_index {|i| puts "#{i}\t#{list[i]["site"]}"} 
    else break
    end
  end

  # interpret index - no bounds checking, yet ...
  if site =~ /^[0-9]*$/ 
  then
    salt = list[site.to_i]["salt"]
    site = list[site.to_i]["site"]
  elsif site == "q"
  then exit true
  else
    new_site = "y"
    list.each {|entry| if entry["site"] == site then new_site = "n" end}
    if new_site == "y"
    then
      print "New site name detected.  Make a record? [Y/n] "
      if ! (gets.chomp =~ /^[Nn]$/)
      then
        salt = `dd if=/dev/urandom bs=1 count=1024 2>/dev/null | base64 --wrap=0`
        list_file_handle = File.open list_file_name, "a"
        list_file_handle.puts "#{salt} #{site}"
        list_file_handle.close
      end
    end
  end

  hash = ""

  # Massage the hash into a password likely to work with any website.
  # Rehash if it doesn't have certain characteristics.
  begin
    # Hash salt, password, site name, and (after first iteration) old hash.
    hash = `echo \"#{salt}#{password}#{site}#{hash}\" | sha512sum -`
    hash.sub(/\ -\ /, '')
    # First eight characters only.
    hash = hash[0..8]
  end while (hash =~ /^[a-z]*$/ || (!(hash =~ /[a-z].*[a-z]/)) )
  # above:  not all letters, minimum two letters

  # Pick a character to capitalize at not-quite-random.
  cap_index = (hash[0] + hash[1] + hash[2]) % 8

  # Increment cap_index until it indexes a character.
  temp_hash = ""
  temp_hash.concat hash[cap_index]
  while ! (temp_hash =~ /[a-z]/)
    cap_index += 1
    if cap_index == 8 then cap_index = 0 end
    temp_hash.concat hash[cap_index]
  end

  # Capitalize chosen character.
  temp_hash = ""
  old_hash = hash
  hash = ""
  for c in 0..7
    if c == cap_index
      temp_hash.concat old_hash[c]
      hash.concat temp_hash.capitalize
    else 
      hash.concat old_hash[c]
    end
  end


  system "printf \"%s\" \"#{hash}\" | xclip -i"
  puts "Password is ready to paste."
end
